<?php
//make registered email address become to the account name 
function yeaoh_email_registration_name($edit, $account){
$edit = array('name' => $account->mail);
return $edit;
}


function yeaoh_form_comment_form_alter(&$form,&$form_state,$form_id){

    if($form['#node']->type="awb_tracking"){

      $nid = $form['#node']->nid;
      $cid = db_query('select cid from {comment}  where nid =:nid  order by cid desc LIMIT 0 , 1',array(':nid'=>$nid))->fetchfield();
      if($cid!=null){

      $comment = comment_load($cid);
      $form['field_from']['und'][0]['value']['#default_value'] = empty($comment->field_from['und'][0]['value'])?'':$comment->field_from['und'][0]['value'];
      $form['field_to']['und'][0]['value']['#default_value'] = empty($comment->field_to['und'][0]['value'])?'':$comment->field_to['und'][0]['value'];
      $form['field_pieces']['und'][0]['value']['#default_value'] = empty($comment->field_pieces['und'][0]['value'])?'':$comment->field_pieces['und'][0]['value'];
      $form['field_kilos']['und'][0]['value']['#default_value'] = empty($comment->field_kilos['und'][0]['value'])?'':$comment->field_kilos['und'][0]['value'];
      $form['field_comments']['und'][0]['value']['#default_value'] = empty($comment->field_comments['und'][0]['value'])?'':$comment->field_comments['und'][0]['value'];
      $form['field_date_time']['und'][0]['value']['#default_value'] = empty($comment->field_date_time['und'][0]['value'])?'':$comment->field_date_time['und'][0]['value'];
      $form['field_status']['und']['#default_value'] = empty($comment->field_status['und'][0]['value'])?'':$comment->field_status['und'];
      }

      //echo'<pre>'; print_r($comment); exit;
      $form['#submit'][] = 'send_comment_email';
      $form['#submit'][] = 'yeaoh_comments_comments_form_submit';


    }

}
 function yeaoh_comments_comments_form_submit($form, &$form_state){

   $idd=$form_state['values']['subject'];

  if(arg(2)=="edit"){
   drupal_set_message("Tracking line ".$idd." has been updated");
  }else{
    drupal_set_message("Tracking line ".$idd." has been created");
  }

 

}


function send_comment_email(&$form,&$form_state){

  $nid  = $form_state['values']['nid'];
  $node = node_load($nid);
   $arr = array();

  if(!empty($node->field_user['und'][0]['user'])){
   $customer = $node->field_user['und'][0]['user'];
   $customer_email =  $customer->mail;
	  if(!in_array($customer_email,$arr)){
	     $arr[] = $customer_email;
	  }
   }

    if(!empty($node->field_email['und'])){
      foreach($node->field_email['und'] as $mails){

	  if(!in_array($mails['email'],$arr)){
		$arr[] = $mails['email'];
	  }

      }

    }





   
  if(!empty($form_state['values']['field_notification'])){
     if($form_state['values']['field_notification']['und'][0]['value']==1){

	$status  = '';
 	if($form_state['values']['field_status']['und'][0]['value'] == 1){
	 $status = 'Picked up';
	}elseif($form_state['values']['field_status']['und'][0]['value'] == 2){
	 $status = 'In transit';
        }elseif($form_state['values']['field_status']['und'][0]['value'] == 3){
	 $status = 'Delivered';
	}elseif($form_state['values']['field_status']['und'][0]['value'] == 4){
	 $status = 'Other-refer to Comments';
	}


    foreach($arr as $mail){

     $module = 'yeaoh';
     $key = 'yeaoh';
     $language = language_default();
     $params = array(
      '@url' => url('node/' . $node->nid, array('absolute' => TRUE)),
      '@title' => $node->title,
      '@email'=>variable_get('site_mail'),
      '@from'=>$form_state['values']['field_from']['und'][0]['value'],
      '@to'=>$form_state['values']['field_to']['und'][0]['value'],
      '@status'=>$status,
      '@pieces'=>$form_state['values']['field_pieces']['und'][0]['value'],
      '@comments'=>$form_state['values']['field_comments']['und'][0]['value'],
      '@kilos'=>$form_state['values']['field_kilos']['und'][0]['value'],
      '@date'=>$form_state['values']['field_date_time']['und'][0]['value'],
      '@receiver_email' =>$mail,
    );
 	  $message = drupal_mail($module, $key, $mail, $language, $params);

 	}

     }
  }

}

/**
 * Implements hook_mail().
 */
function yeaoh_mail($key, &$message, $params) {
  $message['subject'] = t("Your AWB @title has been updated", $params);
  $message['body'] = array();
  $message['body'][] = t('Your AWB @title has been updated as followed:',$params);
  $message['body'][] = t("Trace from: @from", $params);
  $message['body'][] = t("To: @to", $params);
  $message['body'][] = t("Status: @status", $params);
  $message['body'][] = t("Kilos: @kilos kgs", $params);
  $message['body'][] = t("Pieces: @pieces", $params);
  $message['body'][] = t("Date/Time: @date", $params);
  $message['body'][] = t("Comments: @comments", $params);

  $message['body'][] = t("For more information please visit @url. If you have any question regarding this update or any inquiry please contact us at @email", $params);
  $message['body'][] = t("This message is intended for the following e-mail address: @receiver_email. If this message is not for you, please delete it.", $params);


}

/**
* Implements hook_block_info().
*/
function yeaoh_block_info() {
  $blocks['trace_search'] = array(
    'info' => t('Trace Your Air Waybill'),
    'region'=>-1,
  );

  return $blocks;
}

function yeaoh_menu(){

   $items['trace/noresult'] = array(
     'page callback' => 'trace_noresult',
     'access callback' =>true,
     'title'=>t('Trace Your Air Waybill'),
  );

   $items['trace/result/%'] = array(
     'page callback' => 'trace_result',
     'access callback' =>true,
     'title'=>t('Trace Your Air Waybill'),
  );

 return $items;
}

function yeaoh_menu_alter(&$items){

 $items['comment/reply/%node']['title'] = 'Add new track line';

}



/**
* Implements hook_block_view().
*/
function yeaoh_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'trace_search':
      $block['title'] = t('Trace Your Air Waybill');
      $block['content'] = drupal_get_form('trace_form');
      break;
  }
  return $block;
}

function trace_form($form, &$form_state){


 drupal_add_js('jQuery(document).ready(function () { jQuery("#clear").click(function(){  jQuery("#trace-form .form-text").val("")}); });', 'inline');

 $form['awb_prefix'] = array(
   '#type'=>'textfield',
   '#title'=>t('Enter Air Waybill Prefix and number here:'), 
   '#size'=>15,
   '#maxlength'=>128,
 );

 $form['awb_number'] = array(
   '#type'=>'textfield',
   '#title'=>t('-'), 
   '#size'=>15,
   '#maxlength'=>128,
 );
 $form['title'] = array(
   '#type'=>'textfield',
   '#title'=>t('Or Full AWB Number here:'), 
   '#size'=>15,
   '#maxlength'=>128,
 );

 $form['submit'] = array(
   '#type'=>'submit',
   '#value'=>t('Trace'),   
 );

 $form['clear'] = array(
   '#markup'=>'<input  type="button" value="clear" class="form-submit" name="clear" id="clear" />',
 );



 return $form;
}

function trace_form_submit(&$form, &$form_state){

  $prefix = $form_state['values']['awb_prefix'];
  $number = $form_state['values']['awb_number'];
  $title = $form_state['values']['title'];
  $result = '';

 if($title=='' &&$prefix=='' && $number==''){
    $form_state['redirect'] = 'trace/noresult';
    return;
 }elseif($title!='' &&$prefix=='' && $number==''){
  $nids =  db_query('select nid from {node} where title = :title and type = :type and status = 1',array(
	':title'=>$title,
	':type'=>'awb_tracking'
	));
   $result = $title;
 }elseif($title!='' &&$prefix!='' && $number!=''){

    $nids =  db_query('select nid from {node} where title = :title and type = :type and status = 1 or title =:awb',array(
	':title'=>$title,
	':type'=>'awb_tracking',
	':awb'=>$prefix.$number,
	));

   $result = $title.'&'.$prefix.$number;

 }elseif($title=='' &&$prefix!='' && $number!=''){
  $nids =  db_query('select nid from {node} where title = :title and type = :type and status = 1',array(
	':title'=>$prefix.$number,
	':type'=>'awb_tracking'
	));
   $result = $prefix.$number;

 }elseif($title=='' &&$prefix!='' && $number==''){
  $nids =  db_query('select nid from {node} where title = :title and type = :type and status = 1',array(
	':title'=>$prefix,
	':type'=>'awb_tracking'
       ));
   $result = $prefix;

 }elseif($title=='' &&$prefix=='' && $number!=''){
  $nids =  db_query('select nid from {node} where title = :title and type = :type and status = 1',array(
	':title'=>$number,
	':type'=>'awb_tracking'
       ));
   $result = $number;

 }


$str_nid = '';
$count = 0; 
foreach($nids as $nid){
 $str_nid = $nid->nid;
$count++;
}

 if($str_nid==''){
     $form_state['redirect'] = 'trace/noresult';
     return;
 }

  if($count == 1){
     $form_state['redirect'] = 'node/'.$str_nid;
   }else{
     $form_state['redirect'] = 'trace/result/'.$result;
   }

 


}


function trace_result(){


  if(strpos(arg(2),'&')){

  $arr = explode('&',arg(2));


  $nids =  db_query('select * from {node} where title = :title or title =:title1 and type = :type and status = 1',array(
	':title'=>$arr[0],
	':title1'=>$arr[1],
	':type'=>'awb_tracking'
	));
  }else{
  $nids =  db_query('select * from {node} where title = :title and type = :type and status = 1',array(
	':title'=>arg(2),
	':type'=>'awb_tracking'
	));
 }
$output = '';

foreach($nids as $nid){
   $output .= '<div><a href="/node.'.$nid->nid.'">'.$nid->title.'</a></div>';
}

return $output;

}

function trace_noresult(){

     $output = '<p>There is no data matching your input and criterion. Please correct and check again. If you think you receive this message by error, please <a href="/contact">contact us</a></p>';

 return $output;

}


function yeaoh_menu_local_tasks_alter(&$data, $router_item, $root_path) {
 
  $parm = arg(1);
  $nid = empty($parm)?0:$parm;
  $node = node_load($nid);
  if($node!=null && $node->type == 'awb_tracking'){

  $data ['tabs'][0]['output'][] = array(
    '#theme' => 'menu_local_task',
    '#link' => array(
      'title' => t('Track'),
      'href' => 'comment/reply/'.arg(1).'',
      'localized_options' => array(
        'attributes' => array(
          'title' => t('Track'),
        ),
      ),
    ),
    // Define whether this link is active. This can be omitted for
    // implementations that add links to pages outside of the current page
    // context.
   // '#active' => ($router_item ['path'] == $root_path),
  );

$data['tabs']['0']['count'] = $data['tabs']['0']['count'] + 1;

}

}


